### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by Gabian34** [codetheweb/MMM-AnyList#35] opened 2023-10-29 09:01 UTC
Hello,

Since 2 days I got this message error INIT notification HTTP Error service unavailable code 503.No change from my side, everything was OK before. Other modules are OK. 
Any idea ?
Thanks for your answer...

**Comment by BenJamesFX** [comment] 2023-10-29 13:15
Hey,
I am having the exact same problem aswell!
I thought it was at my end...spent last two days trying to sort with no joy.

Hopefully it gets fixed soon!

Many Thanks

**Comment by codetheweb** [comment] 2023-10-30 04:09
Duplicate of https://github.com/codetheweb/anylist/issues/34

**Closed by codetheweb** 2023-10-30 04:09 UTC
